import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  text: {
    fontFamily: 'Roboto',
  },
  inactivePeriod: {
    color: '#D5DEEB',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  activePeriod: {
    color: '#383c4d',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  bigText: {
    color: '#383c4d',
    fontSize: 24,
    fontWeight: 'bold',
  },
  buttonText: {
    color: '#383c4d',
    fontWeight: 'bold',
  },
  verificationCode: {
    position: 'absolute',
    top: -35,
    right: -25,
    bottom: 0,
    left: 0,
    textAlign: 'right',
    color: '#fff',
    fontWeight: 'bold',
  },
  verificationPhrase: {
    position: 'absolute',
    top: 0,
    width: '100%',
    textAlign: 'right',
    color: '#fff',
    fontWeight: 'bold',
    paddingRight: 15,
    paddingTop: 5,
  },
  verificationIcon: {
    color: '#6179f2',
  },
  walletWraper: {
    backgroundColor: '#f5f9fc',
    paddingTop: 50,
    paddingHorizontal: 15,
  },
  idCard: {
    backgroundColor: '#627ffc',
    height: 150,
    borderWidth: 1,
    borderColor: '#6179f2',
    borderRadius: 15,
    marginTop: 15,
    marginHorizontal: 0,
    marginBottom: 25,
    paddingHorizontal: 15,
    paddingVertical: 10,
    overflow: 'hidden',
  },
  calendarCard: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#fff',
    borderRadius: 15,
    marginTop: 15,
    marginHorizontal: 0,
    marginBottom: 25,
    paddingHorizontal: 15,
    paddingVertical: 10,
    overflow: 'hidden',
  },
  passText: {
    flexDirection:'row',
    flexWrap:'wrap',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    marginTop: 25,
  },
  idName: {
    color: '#fff',
    textAlign: 'left',
    fontWeight: 'bold',
    fontSize: 32,
  },
  validation: {
    marginLeft: 5,
    textAlign: 'center',
    backgroundColor: '#758cff',
    fontSize: 8,
    fontWeight: 'bold',
    color: '#fff',
    borderWidth: 1,
    borderColor: '#758cff',
    borderRadius: 5,
    paddingVertical: 2,
    paddingHorizontal: 8,
    overflow: 'hidden',
  },
  timestamp: {
    fontSize: 10,
    color: '#c8d3f7',
    marginTop: 15,
    marginBottom: 5,
  },
  popUp: {
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
    elevation: 100,
  },
  popUpDialog: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 15,
    zIndex: 100,
    elevation: 100,
    backgroundColor: '#fff',
  },
  qrBody: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  dismissButton: {
   position: 'absolute',
   bottom: 0,
   left: 0,
   right: 0,
   marginHorizontal: 'auto',
   marginBottom: -50,
   width: 55,
   height: 55,
   borderRadius: 85/2,
   backgroundColor: '#627ffc',
   justifyContent: 'center',
   alignItems: 'center',
   shadowColor: 'black',
   shadowRadius: 8,
   shadowOpacity: 0.12,
   opacity: 1,
   zIndex: 10,
},
  actionButtons: {
    flexDirection: 'row',
    flexWrap:'wrap',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    marginBottom: 25,
    paddingHorizontal: 2,
  },
  scanButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '49%',
    height: 50,
    backgroundColor: '#f5f9fc',
  },
  addValueButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '49%',
    height: 50,
    marginLeft: '2%',
    backgroundColor: '#bccce0',
  }
})
